gmtclient/src/main/java/org/gmt/rest/client/model/Category.java
/**
 * 
 */
package org.gmt.rest.client.model;


/**
 * 
 * @author Ralf Mehle
 */
public class Category
{
    private String category;
    private Long id;
   
    
    /**
     * @return the category
     */
    public String getCategory()
    {
        return category;
    }
    
    /**
     * @param category the category to set
     */
    public void setCategory(String category)
    {
        this.category = category;
    }
    
    /**
     * @return the id
     */
    public Long getId()
    {
        return id;
    }
    
    /**
     * @param id the id to set
     */
    public void setId(Long id)
    {
        this.id = id;
    }        
}

gmtclient/src/main/java/org/gmt/rest/client/model/Goal.java
/**
 * 
 */
package org.gmt.rest.client.model;

import java.time.LocalDateTime;
import java.util.List;

import org.gmt.persistence.model.Category;
import org.gmt.persistence.model.Status;


/**
 * 
 * @author Ralf Mehle
 */
public class Goal
{
    private LocalDateTime beginDate;
    private LocalDateTime endDate;
    private String description;
    private String shortTerm;
    private Long id;
    private Category category;
    private Status status;
    private List<SubGoal> subGoals;
    private Boolean notifications;
   
    
    /**
     * @return the beginDate
     */
    public LocalDateTime getBeginDate()
    {
        return beginDate;
    }
    
    /**
     * @param beginDate the beginDate to set
     */
    public void setBeginDate(LocalDateTime beginDate)
    {
        this.beginDate = beginDate;
    }
    
    /**
     * @return the endDate
     */
    public LocalDateTime getEndDate()
    {
        return endDate;
    }
    
    /**
     * @param endDate the endDate to set
     */
    public void setEndDate(LocalDateTime endDate)
    {
        this.endDate = endDate;
    }
    
    /**
     * @return the description
     */
    public String getDescription()
    {
        return description;
    }
    
    /**
     * @param description the description to set
     */
    public void setDescription(String description)
    {
        this.description = description;
    }
    
    /**
     * @return the shortTerm
     */
    public String getShortTerm()
    {
        return shortTerm;
    }
    
    /**
     * @param shortTerm the shortTerm to set
     */
    public void setShortTerm(String shortTerm)
    {
        this.shortTerm = shortTerm;        
    }
    
    /**
     * @return the id
     */
    public Long getId()
    {
        return id;
    }
    
    /**
     * @param id the id to set
     */
    public void setId(Long id)
    {
        this.id = id;
    }
    
    /**
     * @return the category
     */
    public Category getCategory()
    {
        return category;
    }
    
    /**
     * @param string the category to set
     */
    public void setCategory(Category string)
    {
        this.category = string;
    }
    
    /**
     * @return the status
     */
    public Status getStatus()
    {
        return status;
    }
    
    /**
     * @param status2 the status to set
     */
    public void setStatus(Status status2)
    {
        this.status = status2;
    }
    
    /**
     * @return the subGoals
     */
    public List<SubGoal> getSubGoals()
    {
        return subGoals;    
    }
    
    /**
     * @param subGoals the subGoals to set
     */
    public void setSubGoals(List<SubGoal> subGoals)
    {
        this.subGoals = subGoals;
    }
    
    /**
     * @return the notifications
     */
    public Boolean getNotifications()
    {
        return notifications;
    }
    
    /**
     * @param notifications the notifications to set
     */
    public void setNotifications(Boolean notifications)
    {
        this.notifications = notifications;
    }     
    
    /**
     * Reset all fields to default values
     */
    public void clear()
    {
	 beginDate = null;
	 endDate = null;
	 description = "";
	 shortTerm = "";
	 category = Category.UNKNOWN;
	 status = Status.UNKNOWN;
	 subGoals = null;
	 notifications = true;
    }
}

gmtclient/src/main/java/org/gmt/rest/client/model/Milestone.java
/**
 * 
 */
package org.gmt.rest.client.model;

import java.util.List;

/**
 * 
 * @author Ralf Mehle
 */
public class Milestone
{
    private String description;
    private String name;
    private Long id;
    private Boolean notifications;
    private List<String> todosFinished;
  
    
    /**
     * @return the description
     */
    public String getDescription()
    {
        return description;
    }
    
    /**
     * @param description the description to set
     */
    public void setDescription(String description)
    {
        this.description = description;
    }
    
    /**
     * @return the name
     */
    public String getName()
    {
        return name;
    }
    
    /**
     * @param name the name to set
     */
    public void setName(String name)
    {
        this.name = name;
    }
    
    /**
     * @return the id
     */
    public Long getId()
    {
        return id;
    }
    
    /**
     * @param id the id to set
     */
    public void setId(Long id)
    {
        this.id = id;
    }
    
    /**
     * @return the notifications
     */
    public Boolean getNotifications()
    {
        return notifications;
    }
    
    /**
     * @param notifications the notifications to set
     */
    public void setNotifications(Boolean notifications)
    {
        this.notifications = notifications;
    }
    
    /**
     * @return the todosFinished
     */
    public List<String> getTodosFinished()
    {
        return todosFinished;
    }
    
    /**
     * @param todosFinished the todosFinished to set
     */
    public void setTodosFinished(List<String> todosFinished)
    {
        this.todosFinished = todosFinished;
    }       
}

gmtclient/src/main/java/org/gmt/rest/client/model/Status.java
/**
 * 
 */
package org.gmt.rest.client.model;


/**
 * 
 * @author Ralf Mehle
 */
public class Status
{
    private String status;
    private Long id;
    
    
    /**
     * @return the status
     */
    public String getStatus()
    {
        return status;
    }
    
    /**
     * @param status the status to set
     */
    public void setStatus(String status)
    {
        this.status = status;
    }
    
    /**
     * @return the id
     */
    public Long getId()
    {
        return id;
    }
    
    /**
     * @param id the id to set
     */
    public void setId(Long id)
    {
        this.id = id;
    }      
}

gmtclient/src/main/java/org/gmt/rest/client/controller/CategoryController.java
/**
 * 
 */
package org.gmt.rest.client.controller;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.gmt.rest.client.CategoryClient;
import org.gmt.rest.client.model.Category;


/**
 * The BackingBean 'CategoryController' controls CRUD operations for categories. 
 * @author Ralf Mehle
 */
@Named
@RequestScoped
public class CategoryController implements Serializable
{
    private static final long serialVersionUID = 1L;
    
    @Inject
    private CategoryClient categoryClient;
    private Map<String,Object> allCategories;

    
    @PostConstruct
    public void init() 
    {
	// Gets all categories defined via REST-API call
	List<Category> categories = categoryClient.getAllCategories();
	
	allCategories = new LinkedHashMap<String,Object>();
	for (Category tempCategory : categories)
	{
	    allCategories.put(tempCategory.getCategory().toString(), tempCategory.getCategory());
	}     
    }  
    
    /**
     * Gets all categories 
     * 
     * @return	allCategories	the categories
     */
    public Map<String,Object>  getAllCategories()
    {	
	return allCategories;
    }
}

gmtclient/src/main/java/org/gmt/rest/client/controller/GoalController.java
/**
 * 
 */
package org.gmt.rest.client.controller;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

import org.gmt.rest.client.GoalClient;
import org.gmt.rest.client.model.Goal;
import org.gmt.rest.client.view.GoalTimeline;
import org.primefaces.event.timeline.TimelineModificationEvent;
import org.primefaces.model.timeline.TimelineModel;


/**
 * The BackingBean 'GoalController' controls CRUD operations for goals. 
 * 
 * @author Ralf Mehle
 */
@Named
@ViewScoped
public class GoalController implements Serializable
{
    private static final long serialVersionUID = 1L;
    
    @Inject
    private GoalClient goalClient;
    private List<Goal> goals;
    private Goal goal;
    private List<String> subGoals;   	// just a placeholder...
    private GoalTimeline goalTimeline;
    private String buttonValue;     	// label string for save/update button 
    private Long goalId = -1L;		// for deletion ...
    
    
    @PostConstruct
    public void init() 
    {        
	goal = new Goal();
	
	subGoals = new ArrayList<String>();
	subGoals.add("test");
	
	goals = goalClient.getAllGoals();	
	goalTimeline = new GoalTimeline(goals);
    }       
        
    /**
     * @return the goal
     */
    public Goal getGoal()
    {
        return goal;
    }
    
    /**
     * @param goal the goal to set
     */
    public void setGoal(Goal goal)
    {
        this.goal = goal;
    }
    
    /**
     * @return the subGoals
     */
    public List<String> getSubGoals()
    {
        return subGoals;
    }
    
    /**
     * @param subGoals the subGoals to set
     */
    public void setSubGoals(List<String> subGoals)
    {
        this.subGoals = subGoals;
    }
    
    /**
     * @return the goalTimeline
     */
    public GoalTimeline getGoalTimeline()
    {
        return goalTimeline;
    }
    
    /**
     * @param goalTimeline the goalTimeline to set
     */
    public void setGoalTimeline(GoalTimeline goalTimeline)
    {
        this.goalTimeline = goalTimeline;
    }
    
    /**
     * @return the buttonValue
     */
    public String getButtonValue()
    {
	return buttonValue;
    }

    /**
     * @param buttonValue the buttonValue to set
     */
    public void setButtonValue(String buttonValue)
    {
	this.buttonValue = buttonValue;
    }
    
    /**
     * Returns the GoalTimeLineModel
     * 
     * @return	the goal TimeLineModel
     */
    public TimelineModel getGoalTimelineModel()
    {	
	return goalTimeline.getGoalTimelineModel();	
    }
        
    /**
     * Save a new goal in the backend via REST-API
     * 
     * @return	responseMsg	the response message as string
     */
    public String saveNewGoal()
    {
	// add subgoals and milestones before saving
	String responseMsg = goalClient.createGoal(goal);
	doPageReload();
	
	return responseMsg;
    }
    
    /**
     * Save all subgoals in a goal
     * 
     * @return	an empty string
     */
    public String saveSubGoals()
    {
	//subGoals.put();
	
	return "";	
    }
    
    /**
     * Save all milestones in a subgoal
     * 
     * @return	an empty string
     */
    public String saveMilestone()
    {
	//milestones.put();
	
	return "";	
    }

    /**
     * Saves an edited goal in the backend via REST-API
     * 
     * @return responseMsg
     */
    public String updateGoal()
    {
	// add subgoals and milestones before saving
	String responseMsg = goalClient.updateGoal(goal);
	doPageReload();

	return responseMsg;
    }
           
    /**
     * Deletes a goal by its Id
     * 
     * @return	retVal	the status value returned as integer
     */
    public Integer deleteGoal()
    {
	Integer retVal = goalClient.deleteGoalById(goalId);
	doPageReload();
	
	return retVal;
    }
    
    /**
     * Performs actions on creating a new goal 
     */
     public void onNew()
    {
	setButtonValue("Save");   // set label string to "Save"
    }
    
    /**
     * Gets the goal being edited via REST-API
     * 
     * @param	eventMod	the TimelineModificationEvent
     */
    public void onEdit(TimelineModificationEvent eventMod)
    {		
	setButtonValue("Update");   // set label string to "Update"
	
	Long goalId = -1L;
	for (Goal tempGoal: goals)
	{
	    String shortTermFromEvent = eventMod.getTimelineEvent().getData().toString();
	    if (tempGoal.getShortTerm().equals(shortTermFromEvent) == true)
	    {
	       goalId = tempGoal.getId();
	       break;
	    }
	}	
	goal = goalClient.getGoalById(goalId);	
    }
        
    /**
     * Delete an existing goal in the backend via REST-API
     * 
     * RF: we need a confirm dialog here instead sleep(): on deletion db needs 
     *     some time to delete multiple records
     *     
     * @param	eventMod	the TimelineModificationEvent
     */
    public void onDelete(TimelineModificationEvent eventMod)
    {	
	for (Goal tempGoal: goals)
	{
	    String shortTermFromEvent = eventMod.getTimelineEvent().getData().toString();
	    if (tempGoal.getShortTerm().equals(shortTermFromEvent) == true)
	    {
	       goalId = tempGoal.getId();
	       break;
	    }
	}	
    }

    /**
     * Triggers page reload 
     */
    public void doPageReload() 
    {
	ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
	try
	{
	    ec.redirect(((HttpServletRequest) ec.getRequest()).getRequestURI());
	} catch (IOException e)
	{
	    e.printStackTrace();
	}
    }
}

gmtclient/src/main/java/org/gmt/rest/client/controller/LoginController.java
/**
 * 
 */
package org.gmt.rest.client.controller;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.gmt.rest.client.UserClient;
import org.gmt.rest.client.model.User;


/**
 * The BackingBean 'LoginController' controls login and logout of a user. 
 * 
 * FT: A spinner would be fine. The user logs in and gets no indication
 *     what happens during the login process.
 * 
 * @author Ralf Mehle
 */
@Named
@RequestScoped
public class LoginController implements Serializable
{
    private static final long serialVersionUID = 1L;
    
    private String username;
    private String password;
    
    @Inject
    private UserClient userClient;
    private List<User> users;
       
    
    /**
     * @return the username
     */
    public String getUsername()
    {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username)
    {
        this.username = username;
    }

    /**
     * @return the password
     */
    public String getPassword()
    {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password)
    {
        this.password = password;
    }
    
    /**
     * Login a valid user, reject an invalid one
     * 
     * @return retVal	the redirect string to the page after login procedure
     */
    public String login()
    {		
	String retVal = "";
	FacesContext context = FacesContext.getCurrentInstance();
	
	users = userClient.getAllUsers();
	for (User tempUser : users)
	{
	    if (this.username.equals(tempUser.getUsername()) && 
		    this.password.equals(tempUser.getPassword()))
	    {
		context.getExternalContext().getSessionMap().put("user", username);
		//context.getExternalContext().redirect("main.xhtml");
		retVal = "main";
		break;
	    }
	    else
	    {
		retVal = "reject";
	    }
	}
	return retVal;
    }
}

gmtclient/src/main/java/org/gmt/rest/client/controller/LogoutController.java
/**
 * 
 */
package org.gmt.rest.client.controller;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;


/**
 * LogoutController called when logout is performed
 * 
 * @author Ralf Mehle
 */
@Named
@RequestScoped
public class LogoutController
{
    /**
     * Logout
     * 
     * @return "login"
     */
    public String logout() 
    {
	FacesContext context = FacesContext.getCurrentInstance();
	context.getExternalContext().invalidateSession();

        return "login";
    }
}

gmtclient/src/main/java/org/gmt/rest/client/controller/StatusController.java
/**
 * 
 */
package org.gmt.rest.client.controller;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.gmt.rest.client.StatusClient;
import org.gmt.rest.client.model.Status;


/**
 * The BackingBean 'StatusController' controls CRUD operations for status. 
 * 
 * @author Ralf Mehle
 */
@Named
@RequestScoped
public class StatusController implements Serializable
{
    private static final long serialVersionUID = 1L;
    
    @Inject
    private StatusClient statusClient;
    private Map<String,Object> allStatus;

    
    @PostConstruct
    public void init() 
    {
	// Gets all status defined via REST-API call
	List<Status> status = statusClient.getAllStatus();
	
	allStatus = new LinkedHashMap<String,Object>();
	for (Status tempStatus : status)
	{
	    allStatus.put(tempStatus.getStatus().toString(), tempStatus.getStatus());
	}     
    }    
    
    /**
     * Returns all status
     * 
     * @return	allStatus	a map containing all status 
     */
    public Map<String,Object> getAllStatus()
    {	
	return allStatus;
    }
}

gmtclient/WebContent/index.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<h:head>
		<title><h:outputText value="GMT - Goal Management Tool" /></title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<h:outputStylesheet name="styles/gmtstyles.css"/>	
	</h:head>
	<h:body class="main">
		<div class="in_div">
			<h:form>
				<h1 class="in_h1">
					<h:outputText class="in_h1_outputtext" value="GMT - Goal Management Tool" />
				</h1>
				<h:outputText class="in_outputtext" value="“A dream is just a dream. A goal is a dream with a plan and a deadline.” ― Harvey MacKay" />		
				<p:commandButton value="Let's go!" class="in_link" action="login" ajax="false" />
			</h:form>
		</div>
	</h:body>
</html>

gmtclient/WebContent/login.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title><h:outputText value="GMT - Goal Management Tool" /></title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<h:outputStylesheet name="styles/gmtstyles.css" />
</h:head>
<h:body class="main">
	<div>
		<div class="lg_divtop">
			<h1 class="lg_h1">
				<h:outputText class="lg_h1_outputtext" value="GMT - Goal Management Tool" />
			</h1>
		</div>
		<div class="lg_divmain">
			<h:form>
				<h:panelGrid class="lg_pgridmain" columns="2" cellpadding="10"
					cellspacing="1">
					<f:facet name="header">
						<h:outputText value="Login" />
					</f:facet>
					<h:outputLabel value="Username:" />
					<h:inputText value="#{loginController.username}" label="username" />

					<h:outputText value="Password:" />
					<h:inputSecret value="#{loginController.password}" label="password" />

					<f:facet name="footer">
						<h:panelGroup class="lg_pgroup">
							<p:commandButton class="lg_btn" value="Submit" action="#{loginController.login}"/>
							<p:commandButton class="lg_btn" value="Cancel" action="index" />
						</h:panelGroup>
					</f:facet>
				</h:panelGrid>
			</h:form>
		</div>
	</div>
</h:body>
</html>

gmtclient/WebContent/main.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">

<h:head>
	<title><h:outputText value="GMT - Goal Management Tool" /></title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<h:outputStylesheet name="styles/gmtstyles.css" />
</h:head>
<h:body class="main">
	<h:form id="form1">
		<div id="globdiv">
			<div id="mndivtop" class="mn_divtop">
				<p:panelGrid>
					<h1 class="mn_h1">
						<h:outputText class="mn_h1_outputtext" value="GMT - Goal Management Tool" />
					</h1>
					<p:commandButton style="position: absolute; top: 12px; left: 93%;" value="Logout" action="#{logoutController.logout}" />
				</p:panelGrid>
			</div>
			<div id="mndivmain" class="mn_divmain">
				<p:timeline id="timeline" widgetVar="timeLine" value="#{goalController.goalTimelineModel}" height="400px" width="1100px" 
					showCurrentTime="true" style="position: absolute; left: 10%; right: 10%" 
					timeChangeable="false" stackEvents="true" editable="true" eventMargin="10" eventMarginAxis="0" 
					min="#{goalController.goalTimeline.startEvent}">
					<p:ajax event="edit" listener="#{goalController.onEdit}" update="goalDialog" oncomplete="PF('goalDlg').show()" />
					<p:ajax event="delete" listener="#{goalController.onDelete}" onstart="PF('confirm').show()"/>					
				</p:timeline>
				<p:confirmDialog widgetVar="confirm" message="Are you sure?" header="Confirm goal deletion" severity="alert" >
					<p:commandButton value="OK" action="#{goalController.deleteGoal}"
						style="left: 135px" oncomplete="PF('confirm').hide()"/>
					<p:commandButton value="Cancel" update="form1:timeline" onclick="PF('confirm').hide()" 
						style="position: absolute; right: 10px" />
				</p:confirmDialog>
			</div>
			<div class="mn_divbottom">
				<p:commandButton id="newGoal" styleClass="mn_btngreen" style="position: absolute; top: 90%; left: 46%;" value="New Goal"
					oncomplete="PF('goalDlg').show()" update="goalDialog" resetValues="true" actionListener="#{goalController.onNew}"/>					
			</div>
		</div>
	</h:form>		
	<p:dialog id="goalDialog" widgetVar="goalDlg" visible="#{facesContext.validationFailed}" modal="true" 
		width="800" height="500" resizable="false" >
		<h:form id="form2">
			<p:tabView id="tabView" style="font-size: small">
				<p:tab id="goalTab" title="Goal">	
					<p:panelGrid id="pGrid1" columns="1" cellpadding="10" styleClass="ui-noborder" style="width: 100%; position: relative">
						<h:outputText value="Name:" />
						<p:inputText id="shortTermGoal" value="#{goalController.goal.shortTerm}" required="true" maxlength="255" 
							style="width: 98%">
							<f:validateLength minimum="1"/>
							<p:message for="shortTermGoal" display="icon"/>																													
						</p:inputText>	
						<h:outputText value="Description:" />
						<p:inputTextarea id="descriptionGoal" value="#{goalController.goal.description}" required="true" maxLength="1023" 
							style="width: 98%">			
							<f:validateLength minimum="1"/>
							<p:message for="descriptionGoal" display="icon" />						
						</p:inputTextarea>
					</p:panelGrid>
					<p:panelGrid id="pGrid2" columns="4" cellpadding="10" cellspacing="1" styleClass="ui-noborder" style="width: 100%;
						position: relative;">
						<h:outputLabel for="beginDateTime" value="Begin:" />
						<p:calendar id="beginDateTime" value="#{goalController.goal.beginDate}" pattern="dd.MM.yyyy HH:mm:ss" 
							showOn="button" required="true">
							<f:convertDateTime date-style="medium" type="localDateTime"	pattern="dd.MM.yyyy HH:mm:ss" />
							<f:validateLength minimum="1"/>
							<p:message for="beginDateTime" display="icon" />												
						</p:calendar>
						<h:outputText />
						<h:outputText />
						<h:outputLabel for="endDateTime" value="End:" />
						<p:calendar id="endDateTime" value="#{goalController.goal.endDate}" pattern="dd.MM.yyyy HH:mm:ss" showOn="button"
							required="true">
							<f:convertDateTime date-style="medium" type="localDateTime"	pattern="dd.MM.yyyy HH:mm:ss" />
							<f:validateLength minimum="1"/>
							<p:message for="endDateTime" display="icon" />																		
						</p:calendar>
						<h:outputText />
						<h:outputText />
						<h:outputText value="Category:" />
						<p:selectOneMenu label="selectOneCategory" value="#{goalController.goal.category}">
							<f:selectItems value="#{categoryController.allCategories}" />
						</p:selectOneMenu>
						<h:outputLabel for="colorCat" value="Color:" style="color:grey"/>									
	<!-- 					<p:colorPicker id="colorCat" /> -->
						<h:outputText value="Status:" />
						<p:selectOneMenu label="selectOneStatus" value="#{goalController.goal.status}">
							<f:selectItems value="#{statusController.allStatus}" />
						</p:selectOneMenu>
						<h:outputText />
						<h:outputText />
						<h:outputText value="Subgoals:" style="color:grey"/>		
						<h:outputText />
						<h:outputText />
						<h:outputText />
					</p:panelGrid>
					<p:panelGrid id="pGrid3" styleClass="ui-noborder" style="display:block; margin-left: auto; margin-right: 0">
						<pe:switch id="switch" value="#{goalController.buttonValue}" >  
							<pe:case value="Save">
								<p:commandButton id="actionBtn1" style="position: absolute; right: 115px; background: LimeGreen;" 
									value="Save" actionListener="#{goalController.saveNewGoal}" ajax="false" >
								</p:commandButton>
							</pe:case>  
							<pe:case value="Update">
								<p:commandButton id="actionBtn2" style="position: absolute; right: 115px; background: LimeGreen;" 
									value="Update" action="#{goalController.updateGoal}" ajax="false" />	
							</pe:case>  
						</pe:switch>						
						<p:commandButton id="cancelBtn" style="position: absolute; right: 40px" value="Cancel" 
							action="#{goalController.goal.clear}" oncomplete="PF('goalDlg').hide()" />
					</p:panelGrid>
				</p:tab>
				<p:tab title="Subgoal" disabled="true" />
				<p:tab title="Milestone" disabled="true" />
			</p:tabView>
		</h:form>			
	</p:dialog>	
</h:body>
</html>

gmtclient/WebContent/reject.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title><h:outputText value="GMT - Goal Management Tool" /></title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<h:outputStylesheet name="styles/gmtstyles.css" />
</h:head>
<h:body class="main">
	<h:form>
		<div>
			<div class="rj_divtop">
				<h1 class="rj_h1">
					<h:outputText class="rj_h1_outputtext" value="GMT - Goal Management Tool" />
				</h1>
			</div>
			<div class="rj_divmain">
				<h:panelGrid class="rj_pgridmain" columns="1" cellpadding="10"
					cellspacing="1">
					<h:outputText value="Login failed!" />
					<p:commandButton style="position: relative; left: 4%;" value="Cancel" action="index" />
				</h:panelGrid>
			</div>
		</div>
	</h:form>
</h:body>
</html>